highlighter: rouge
permalink: /blog/:year/:month/:day/:title/
environment: prod
url: "http://alexarntzen.com"  # Sitemap base URL.
plugins:
  - jekyll-scholar
  - jekyll-sitemap
  - jekyll-feed
sass:   
  sass_dir: "assets/css"
defaults: 
  - 
    scope:  
      path: ""
    values:   
      title: "Alex's site"
      description: "This is my site"
    scope:  
      type: "posts"
    values:   
      mathjax: true
      layout: blog